export interface ISinistro {
  ID: number
  DATA: Date
  DANOS_MATERIAIS_VEICULOS: string
  DANOS_MATERIAIS_OBJECTOS: string
  FERIMENTOS: string
  DESCRICAO: string
  RUA: string
  MORADA: string
  CIDADE: string
  SEGURADO_NOME: string
  SEGURADO_IDENTIFICACAO: string
  SEGURADO_IDENTIFICACAO_NUMERO: string
  SEGURADO_APOLICE_NUMERO: string
  SEGURADO_APOLICE_TIPO: string
  SEGURADO_VEICULO_MARCA: string
  SEGURADO_VEICULO_MODELO: string
  SEGURADO_OBSERVACOES: string
  TOMADOR_NOME: string
  TOMADOR_IDENTIFICACAO: string
  TOMADOR_IDENTIFICACAO_NUMERO: string
  TOMADOR_VEICULO_MARCA: string
  TOMADOR_VEICULO_MODELO: string
  TOMADOR_OBSERVACOES: string
}
